<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="relations"
    nsURI="http://relations/1.0" nsPrefix="relations">
  <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="ecore:EClass activities.ecore#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="ecore:EClass activities.ecore#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaitFor" eSuperTypes="#//ControlFlow"/>
  <eClassifiers xsi:type="ecore:EClass" name="WeakWait" eSuperTypes="#//ControlFlow"/>
  <eClassifiers xsi:type="ecore:EClass" name="Guard" eSuperTypes="#//ControlFlow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="ecore:EClass variables.ecore#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnFailure" eSuperTypes="#//ExceptionalFlow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlFlow" abstract="true" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExceptionalFlow" abstract="true" eSuperTypes="#//Relation"/>
</ecore:EPackage>
