<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="variables"
    nsURI="http://variables/1.0" nsPrefix="variables">
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="../Compositions/algorithms.ecore#//Symbol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSet" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policy" eType="#//IterationPolicy"
        containment="true" eOpposite="#//IterationPolicy/set"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IterationPolicy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" lowerBound="1" eType="#//Variable"
        eOpposite="#//Variable/policy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scalar" lowerBound="1"
        eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="ecore:EClass activities.ecore#//Activity" eOpposite="activities.ecore#//Activity/policy"/>
  </eClassifiers>
</ecore:EPackage>
